### PR TITLE
Optimisations, CI workflow, & deploy script

### LINKED ISSUE #189: Add CI Github action

### PR DESCRIPTION
**Pull request by diego-G**
Closes #189 , #188 , #133

### CODE REVIEW

**Comment by rya-sge** [comment]
Closes #131, #61

**Comment by rya-sge** [comment]
Thank you very much for your great work.

For the custom errors, I saw that currently there is no support of it with truffle/ganache for the tests ("expectRevert.unspecified").
I am not sure if it is the good idea to use it if we do not have a way to test the result.

**Comment by diego-G** [comment]
> Thank you very much for your great work.
> 
> For the custom errors, I saw that currently there is no support of it with truffle/ganache for the tests ("expectRevert.unspecified"). I am not sure if it is the good idea to use it if we do not have a way to test the result. [trufflesuite/truffle#5753](https://github.com/trufflesuite/truffle/issues/5753)

Yes, we already discussed the same topic internally. We preferred to include the optimisation because it's significant enough. This [TODO](https://github.com/CMTA/CMTAT/blob/4cb6320ee4704addfc5ca8f616b6162d98e68d9a/test/common/BaseModuleCommon.js#LL110C1-L110C1) in the code should be addressed as soon as Truffle implements the feature. I will open an issue to remember it.

**Comment by rya-sge** [comment]
Ok perfect, thank you for your work

Perhaps it will be possible to test that with Foundry if one day the actual tests are updated.

I think we can add the support of custom errors for the future version **2.4**.

The version 2.3 will be an audited version, recommended by the CMTA, and I am not really comfortable by adding a functionality which is not audited and not entirely tested.

So here the "planning":
1) Release 2.3 in the next weeks.
2) Cherry-pick the different commits or merge the PR
3) Complete the tests when it is available with Truffle or use Foundry

**Comment by rya-sge** [comment]
Commit 4cb6320ee4704addfc5ca8f616b6162d98e68d9a is included in [pull/193](https://github.com/CMTA/CMTAT/pull/193)

**Pull request closed without merging**
