### PR TITLE
[WIP] Debt products support

### PR DESCRIPTION
**Pull request by veorq**

### CODE REVIEW

**Comment by skrafft** [comment]
@veorq @Ardgevald While it works technically,I think we should add all this code into a DebtModule for consistency with the previous structure. Any thoughts ?

**Comment by veorq** [comment]
Makes sense, @Ardgevald can you make corresponding changes?

**Comment by veorq** [comment]
Seems like we can do it here as the debt functionality is an extension, rather than a modification of the initial token (as designed for equity products).

**Comment by rya-sge** [comment]
The code was included in another PR

**Pull request closed without merging**
